// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrlShortner.Data;

#nullable disable

namespace UrlShortner.Data.Migrations
{
    [DbContext(typeof(UrlShortenerDbContext))]
    partial class UrlShortenerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UrlShortner.Models.UrlShortenerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClickCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastVisited")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ClickCount")
                        .IsDescending()
                        .HasDatabaseName("IX_ClickCount");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_CreatedAt");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_IsActive");

                    b.HasIndex("LastVisited")
                        .HasDatabaseName("IX_LastVisited")
                        .HasFilter("[LastVisited] IS NOT NULL");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("IX_OwnerId")
                        .HasFilter("[OwnerId] IS NOT NULL");

                    b.HasIndex("ShortCode")
                        .IsUnique()
                        .HasDatabaseName("IX_ShortCode");

                    b.HasIndex("OwnerId", "IsActive", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_Owner_Active_Created");

                    b.ToTable("UrlEntries", null, t =>
                        {
                            t.HasComment("Shortened URL entries with analytics");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
